"""add_installed_skills_json_to_runtimes

Revision ID: 69f6631b59e4
Revises: 8f7c592bdd12
Create Date: 2026-03-27 18:45:23.433214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69f6631b59e4'
down_revision: Union[str, None] = '8f7c592bdd12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runtimes', sa.Column('installed_skills_json', sa.Text(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runtimes', 'installed_skills_json')
    # ### end Alembic commands ###
