"""create initial room models

Revision ID: 8f7c592bdd12
Revises: 
Create Date: 2026-03-18 22:49:32.342749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7c592bdd12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workspace_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'archived', 'disabled')", name='ck_agents_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=True)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("room_type IN ('dm', 'room')", name='ck_rooms_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_room_type'), 'rooms', ['room_type'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('owner_agent_id', sa.String(length=64), nullable=False),
    sa.Column('contact_agent_id', sa.String(length=64), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_contacts_agent', 'contacts', ['owner_agent_id', 'contact_agent_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('conversation_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("conversation_type IN ('dm', 'room_main', 'topic')", name='ck_conversations_type'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conversations_room', 'conversations', ['room_id', 'created_at'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=64), nullable=False),
    sa.Column('member_type', sa.String(length=32), nullable=False),
    sa.Column('member_user_id', sa.String(length=64), nullable=True),
    sa.Column('member_agent_id', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("(member_type = 'agent' AND member_agent_id IS NOT NULL AND member_user_id IS NULL) OR (member_type = 'user' AND member_user_id IS NOT NULL AND member_agent_id IS NULL)", name='ck_members_target'),
    sa.ForeignKeyConstraint(['member_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_members_agent', 'members', ['room_id', 'member_agent_id'], unique=True, sqlite_where=sa.text("member_type = 'agent' AND member_agent_id IS NOT NULL"))
    op.create_index('uq_members_user', 'members', ['room_id', 'member_user_id'], unique=True, sqlite_where=sa.text("member_type = 'user' AND member_user_id IS NOT NULL"))
    op.create_table('profiles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=False),
    sa.Column('profile_markdown', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('runtimes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('permission_mode', sa.String(length=64), nullable=True),
    sa.Column('allowed_tools_json', sa.Text(), nullable=False),
    sa.Column('disallowed_tools_json', sa.Text(), nullable=False),
    sa.Column('mcp_servers_json', sa.Text(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=True),
    sa.Column('max_thinking_tokens', sa.Integer(), nullable=True),
    sa.Column('skills_enabled', sa.Boolean(), nullable=False),
    sa.Column('setting_sources_json', sa.Text(), nullable=False),
    sa.Column('runtime_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('runtime_id', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('branch_key', sa.String(length=128), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sdk_session_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'idle', 'interrupted', 'closed')", name='ck_sessions_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['runtime_id'], ['runtimes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_agent', 'sessions', ['agent_id', 'last_activity_at'], unique=False)
    op.create_index('idx_sessions_conversation', 'sessions', ['conversation_id', 'last_activity_at'], unique=False)
    op.create_index('uq_sessions_branch', 'sessions', ['conversation_id', 'agent_id', 'branch_key'], unique=True)
    op.create_index('uq_sessions_primary', 'sessions', ['conversation_id', 'agent_id'], unique=True, sqlite_where=sa.text('is_primary = 1'))
    op.create_table('messages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('sender_type', sa.String(length=32), nullable=False),
    sa.Column('sender_user_id', sa.String(length=64), nullable=True),
    sa.Column('sender_agent_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content_preview', sa.Text(), nullable=True),
    sa.Column('jsonl_path', sa.String(length=512), nullable=False),
    sa.Column('jsonl_offset', sa.Integer(), nullable=True),
    sa.Column('round_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("kind IN ('text', 'tool_call', 'tool_result', 'event', 'error')", name='ck_messages_kind'),
    sa.CheckConstraint("sender_type IN ('user', 'agent', 'system', 'tool')", name='ck_messages_sender_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_conversation', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index('idx_messages_session', 'messages', ['session_id', 'created_at'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('round_id', sa.String(length=64), nullable=False),
    sa.Column('trigger_message_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'success', 'error', 'cancelled')", name='ck_rounds_status'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rounds')
    op.drop_index('idx_messages_session', table_name='messages')
    op.drop_index('idx_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_sessions_primary', table_name='sessions', sqlite_where=sa.text('is_primary = 1'))
    op.drop_index('uq_sessions_branch', table_name='sessions')
    op.drop_index('idx_sessions_conversation', table_name='sessions')
    op.drop_index('idx_sessions_agent', table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('runtimes')
    op.drop_table('profiles')
    op.drop_index('uq_members_user', table_name='members', sqlite_where=sa.text("member_type = 'user' AND member_user_id IS NOT NULL"))
    op.drop_index('uq_members_agent', table_name='members', sqlite_where=sa.text("member_type = 'agent' AND member_agent_id IS NOT NULL"))
    op.drop_table('members')
    op.drop_index('idx_conversations_room', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('uq_contacts_agent', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_rooms_room_type'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
