// INPUT: 用户已确认的 exact 草图 preview_id 与 trusted owner/session/round identity。
// OUTPUT: owner-scoped 可复用命名 WorkGraph；原样保存预览中的抽象责任契约与依赖。
// POS: execution-orchestrator Skill 到命名 WorkGraph service 的唯一持久化入口。
package operation

import (
	"context"
	"strings"

	runtimecommand "github.com/nexus-research-lab/nexus/internal/cli/runtimecommand"
	"github.com/nexus-research-lab/nexus/internal/cli/runtimecommand/execution/contract"
	"github.com/nexus-research-lab/nexus/internal/protocol"
)

func distillWorkGraphWorkflow(
	svc contract.WorkflowService,
	sctx contract.Context,
) runtimecommand.Operation {
	const operationName = "distill_workgraph"
	return runtimecommand.Operation{
		Name: operationName,
		Description: "Persist the exact non-expired WorkGraph sketch already generated by the default background model and reviewed by the user. " +
			"The host binds owner and source Session; the command accepts only preview_id and must not reselect nodes or rewrite the sketch.",
		SearchHint:  "save confirmed reusable workgraph sketch preview slash command",
		InputSchema: distillWorkflowSchema(),
		Idempotent:  true,
		ContextHandler: func(
			ctx context.Context,
			input map[string]any,
			call *runtimecommand.CallContext,
		) (runtimecommand.Result, error) {
			var parsed distillWorkflowInput
			if err := decodeInput(input, &parsed); err != nil {
				return transportErrorResult(err), nil
			}
			commandID, err := commandID(sctx, call, operationName, input, 0)
			if err != nil {
				return transportErrorResult(err), nil
			}
			created, err := svc.SavePreview(ctx, strings.TrimSpace(sctx.OwnerUserID), protocol.SaveWorkGraphWorkflowRequest{
				CommandID: commandID, SourceSessionKey: strings.TrimSpace(sctx.ScopeSessionKey),
				PreviewID: strings.TrimSpace(parsed.PreviewID),
			})
			if err != nil {
				return transportErrorResult(err), nil
			}
			return jsonResult(map[string]any{
				"outcome": "applied", "workflow_id": created.ID,
				"slash_name": created.SlashName, "command": "/" + created.SlashName,
				"node_count": len(created.Nodes), "dependency_count": len(created.Dependencies),
				"changed": []string{"workgraph_workflow:" + created.ID},
				"message": "WorkGraph command is ready for reuse in other sessions.",
			}), nil
		},
	}
}
