export const APP_ROUTE_PATHS = {
  landing: "/",
  login: "/login",
  launcher: "/launcher",
  home: "/app",
  room: "/rooms/:room_id",
  room_session: "/rooms/:room_id/sessions/:session_key",
  room_conversation: "/rooms/:room_id/conversations/:conversation_id",
  contacts: "/contacts",
  skills: "/capability/skills",
  skill_detail: "/capability/skills/:skill_name",
  connectors: "/capability/connectors",
  connector_detail: "/capability/connectors/:connector_id",
  connectors_oauth_callback: "/capability/connectors/oauth/callback",
  loops: "/capability/loops",
  loop_detail: "/capability/loops/:slug",
  scheduled_tasks: "/capability/scheduled-tasks",
  channels: "/capability/channels",
  pairings: "/capability/pairings",
  memory: "/memory",
  settings: "/settings",
} as const;

export const AppRouteBuilders = {
  landing: () => APP_ROUTE_PATHS.landing,
  login: () => APP_ROUTE_PATHS.login,
  launcher: () => APP_ROUTE_PATHS.launcher,
  home: () => APP_ROUTE_PATHS.home,
  room: (roomId: string) => `/rooms/${encodeURIComponent(roomId)}`,
  room_session: (roomId: string, sessionKey: string) =>
    `/rooms/${encodeURIComponent(roomId)}/sessions/${encodeURIComponent(sessionKey)}`,
  room_conversation: (roomId: string, conversationId: string) =>
    `/rooms/${encodeURIComponent(roomId)}/conversations/${encodeURIComponent(conversationId)}`,
  contacts: () => APP_ROUTE_PATHS.contacts,
  contact_agent: (agentId: string) => `${APP_ROUTE_PATHS.contacts}?agent=${encodeURIComponent(agentId)}`,
  skills: () => APP_ROUTE_PATHS.skills,
  skill_detail: (skillName: string) => `/capability/skills/${encodeURIComponent(skillName)}`,
  connectors: () => APP_ROUTE_PATHS.connectors,
  connector_detail: (connectorId: string) => `/capability/connectors/${encodeURIComponent(connectorId)}`,
  connectors_oauth_callback: () => APP_ROUTE_PATHS.connectors_oauth_callback,
  loops: () => APP_ROUTE_PATHS.loops,
  loop_detail: (slug: string) => `/capability/loops/${encodeURIComponent(slug)}`,
  scheduled_tasks: () => APP_ROUTE_PATHS.scheduled_tasks,
  channels: () => APP_ROUTE_PATHS.channels,
  pairings: () => APP_ROUTE_PATHS.pairings,
  memory: () => APP_ROUTE_PATHS.memory,
  settings: () => APP_ROUTE_PATHS.settings,
} as const;

type AppRoutePathKey = keyof typeof APP_ROUTE_PATHS;
