export const APP_ROUTE_PATHS = {
  landing: "/",
  login: "/login",
  launcher: "/launcher",
  home: "/app",
  room: "/rooms/:roomId",
  roomSession: "/rooms/:roomId/sessions/:sessionKey",
  roomConversation: "/rooms/:roomId/conversations/:conversationId",
  contacts: "/contacts",
  capability: "/capability",
  skills: "/capability/skills",
  skillDetail: "/capability/skills/:skillName",
  connectors: "/capability/connectors",
  connectorDetail: "/capability/connectors/:connectorId",
  connectorsOauthCallback: "/capability/connectors/oauth/callback",
  loops: "/capability/loops",
  loopDetail: "/capability/loops/:slug",
  workGraphDistillations: "/capability/workgraphs",
  workGraphDistillationDetail: "/capability/workgraphs/:distillationId",
  scheduledTasks: "/capability/scheduled-tasks",
  channels: "/capability/channels",
  pairings: "/capability/pairings",
  operations: "/operations",
  settings: "/settings",
} as const;

export const AppRouteBuilders = {
  landing: () => APP_ROUTE_PATHS.landing,
  login: () => APP_ROUTE_PATHS.login,
  launcher: () => APP_ROUTE_PATHS.launcher,
  home: () => APP_ROUTE_PATHS.home,
  room: (roomId: string) => `/rooms/${encodeURIComponent(roomId)}`,
  roomSession: (roomId: string, sessionKey: string) =>
    `/rooms/${encodeURIComponent(roomId)}/sessions/${encodeURIComponent(sessionKey)}`,
  roomConversation: (roomId: string, conversationId: string) =>
    `/rooms/${encodeURIComponent(roomId)}/conversations/${encodeURIComponent(conversationId)}`,
  contacts: () => APP_ROUTE_PATHS.contacts,
  contactAgent: (agentId: string) => `${APP_ROUTE_PATHS.contacts}?agent=${encodeURIComponent(agentId)}`,
  contactsCreate: () => `${APP_ROUTE_PATHS.contacts}?view=create`,
  contactsManage: () => `${APP_ROUTE_PATHS.contacts}?view=manage`,
  capability: () => APP_ROUTE_PATHS.capability,
  skills: () => APP_ROUTE_PATHS.skills,
  skillDetail: (skillName: string) => `/capability/skills/${encodeURIComponent(skillName)}`,
  connectors: () => APP_ROUTE_PATHS.connectors,
  connectorDetail: (connectorId: string) => `/capability/connectors/${encodeURIComponent(connectorId)}`,
  connectorsOauthCallback: () => APP_ROUTE_PATHS.connectorsOauthCallback,
  loops: () => APP_ROUTE_PATHS.loops,
  loopDetail: (slug: string) => `/capability/loops/${encodeURIComponent(slug)}`,
  workGraphDistillations: () => APP_ROUTE_PATHS.workGraphDistillations,
  workGraphDistillationDetail: (distillationId: string) => `/capability/workgraphs/${encodeURIComponent(distillationId)}`,
  scheduledTasks: () => APP_ROUTE_PATHS.scheduledTasks,
  channels: () => APP_ROUTE_PATHS.channels,
  pairings: () => APP_ROUTE_PATHS.pairings,
  operations: () => APP_ROUTE_PATHS.operations,
  settings: (section?: string) =>
    section
      ? `${APP_ROUTE_PATHS.settings}?section=${encodeURIComponent(section)}`
      : APP_ROUTE_PATHS.settings,
} as const;
